import type { ReportContext } from "./context";

/**
 * Shared report text (spec K1/K6/§9): methodology paragraphs generated from
 * the actual analysis parameters (never hard-coded numbers), the OGL-Canada
 * attribution, and the professional-responsibility disclaimer.
 */

export const OGL_ATTRIBUTION =
  "Contains information licensed under the Open Government Licence – Canada. " +
  "Source data: Environment and Climate Change Canada (ECCC) / Meteorological " +
  "Service of Canada, via the MSC GeoMet OGC API and the ECCC Engineering " +
  "Climate Datasets.";

export const DISCLAIMER =
  "This document was generated by climatePrep to assist a qualified " +
  "professional engineer. All results must be reviewed, interpreted, and " +
  "approved by a licensed engineer before use in design or regulatory " +
  "submissions. The software does not certify results and is not a " +
  "substitute for engineering judgment.";

const DIST_NAMES: Record<string, string> = {
  gumbel: "Gumbel (EV1)",
  gev: "Generalized Extreme Value (GEV)",
  glo: "Generalized Logistic (GLO)",
  pe3: "Pearson Type III (PE3)",
  lp3: "Log-Pearson Type III (LP3)",
};

const METHOD_NAMES: Record<string, string> = {
  lmoments: "L-moments (Hosking & Wallis, 1997)",
  mom: "product-moment (method of moments)",
  mle: "maximum likelihood",
};

export function methodologyParagraphs(ctx: ReportContext): string[] {
  const inputs = ctx.pfaAnalysis.inputs as Record<string, unknown>;
  const dists = (inputs.distributions as string[]) ?? [];
  const method = (inputs.estimationMethod as string) ?? "lmoments";
  const bootstrap = inputs.bootstrap as { n: number; ci: number; seed: number };
  const qcInputs = ctx.qcInputs;

  const pull = ctx.pulls[0];
  const durations = ctx.pfa.durations.map((d) => `${d.durationHours} h`).join(", ");

  const p: string[] = [];

  p.push(
    `Daily precipitation observations for ${ctx.station.stationName} ` +
      `(Climate ID ${ctx.station.climateId}${ctx.station.wmoId ? `, WMO ${ctx.station.wmoId}` : ""}) ` +
      `were obtained from the ECCC Meteorological Service of Canada GeoMet ` +
      `OGC API (collection ${pull?.collection ?? "climate-daily"}), covering ` +
      `${pull?.periodStart ?? "the full record"} to ${pull?.periodEnd ?? "present"}. ` +
      `The station lies at ${ctx.station.latitude.toFixed(4)}°N, ` +
      `${Math.abs(ctx.station.longitude).toFixed(4)}°W` +
      `${ctx.station.elevationM != null ? `, elevation ${ctx.station.elevationM.toFixed(0)} m` : ""}.`,
  );

  const corrFactor = (qcInputs.singleIntervalFactor as number) ?? 1.13;
  const corrApplied = (qcInputs.applyCorrection as boolean) ?? true;
  const completeness = (qcInputs.minYearCompleteness as number) ?? 0.8;
  p.push(
    `Annual maximum series (AMS) were extracted for the ${durations} durations ` +
      `using sliding sums on the daily grid; any window containing missing data ` +
      `was excluded, and years with less than ${(completeness * 100).toFixed(0)}% ` +
      `daily completeness were rejected. ` +
      (corrApplied
        ? `Fixed-to-true interval corrections after WMO-No. 1045 / Weiss (1964) ` +
          `were applied (single-interval factor ${corrFactor.toFixed(2)}; ` +
          `multi-interval factors per the standard table, each logged in the ` +
          `provenance appendix).`
        : `No fixed-to-true interval correction was applied (disabled by the analyst).`),
  );

  p.push(
    `The ${dists.map((d) => DIST_NAMES[d] ?? d).join(", ")} distribution` +
      `${dists.length > 1 ? "s were" : " was"} fitted by ${METHOD_NAMES[method] ?? method}. ` +
      `Goodness of fit was assessed with the Kolmogorov–Smirnov and ` +
      `Anderson–Darling statistics, the probability-plot correlation ` +
      `coefficient (Filliben), and AIC/BIC (log-space likelihoods for LP3 ` +
      `carry the change-of-variables correction). Quantile confidence ` +
      `intervals were estimated by nonparametric bootstrap ` +
      `(n = ${bootstrap?.n ?? 2000}, ${((bootstrap?.ci ?? 0.9) * 100).toFixed(0)}% ` +
      `level, fixed seed ${bootstrap?.seed ?? ctx.seed} for reproducibility).`,
  );

  p.push(
    `Intensity–duration–frequency (IDF) relations were assembled from the ` +
      `${DIST_NAMES[ctx.pfa.idf.distribution] ?? ctx.pfa.idf.distribution} fits across all ` +
      `durations (a single distribution family keeps the IDF surface ` +
      `monotone and matches the methodology of the ECCC published IDF).` +
      (ctx.published
        ? ` The site-specific curves are compared against the ECCC Engineering ` +
          `Climate Datasets published IDF ${ctx.published.version} ` +
          `(${ctx.published.versionDate}; ${ctx.published.method}; record ` +
          `${ctx.published.yearsRange ?? "n/a"}).`
        : ` No ECCC-published IDF exists for this station; the site-specific ` +
          `analysis stands alone.`),
  );

  p.push(
    `All computations were performed by the climatePrep engine ` +
      `v${ctx.engineVersion} (app v${ctx.appVersion}); the complete data and ` +
      `parameter lineage appears in the Provenance appendix.`,
  );

  return p;
}

/** Comparison rows: site vs published depth at shared duration×T points. */
export function comparisonRows(ctx: ReportContext) {
  if (!ctx.published) return [];
  const rows: {
    durationHours: number;
    returnPeriod: number;
    siteMm: number;
    publishedMm: number;
    deltaPct: number;
  }[] = [];
  for (let di = 0; di < ctx.pfa.idf.durationsHours.length; di++) {
    const dur = ctx.pfa.idf.durationsHours[di];
    const pdi = ctx.published.durations.findIndex((d) => d.hours === dur);
    if (pdi === -1) continue;
    for (let ti = 0; ti < ctx.pfa.idf.returnPeriods.length; ti++) {
      const T = ctx.pfa.idf.returnPeriods[ti];
      const pti = ctx.published.returnPeriods.indexOf(T);
      if (pti === -1) continue;
      const cell = ctx.pfa.idf.cells[di][ti];
      const pub = ctx.published.depthsMm[pdi][pti];
      if (!cell || pub === null) continue;
      rows.push({
        durationHours: dur,
        returnPeriod: T,
        siteMm: cell.depth,
        publishedMm: pub,
        deltaPct: ((cell.depth - pub) / pub) * 100,
      });
    }
  }
  return rows;
}
