import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  AggregateRequest,
  AggregateResponse,
  InfillRequest,
  InfillResponse,
  TrendRequest,
  TrendResponse,
} from "@climateprep/core-ts";

/**
 * Contract-parity, TS side (spec §6.1): the fixtures generated by the Python
 * engine (engine/scripts/generate_contract_fixtures.py) must validate against
 * the Zod schemas. pytest validates the same files with pydantic.
 */

const CONTRACT_DIR = path.resolve(__dirname, "../../tests/contract");

function fixture(name: string) {
  return JSON.parse(
    fs.readFileSync(path.join(CONTRACT_DIR, name), "utf8"),
  ) as { request: unknown; response: unknown };
}

describe("Zod ↔ pydantic contract parity", () => {
  it("qc-trend fixture validates", () => {
    const f = fixture("qc-trend.json");
    expect(TrendRequest.safeParse(f.request).success).toBe(true);
    const res = TrendResponse.safeParse(f.response);
    expect(res.success).toBe(true);
    if (res.success) expect(res.data.engineVersion).toBeTruthy();
  });

  it("qc-aggregate fixture validates", () => {
    const f = fixture("qc-aggregate.json");
    expect(AggregateRequest.safeParse(f.request).success).toBe(true);
    const res = AggregateResponse.safeParse(f.response);
    expect(res.success).toBe(true);
    if (res.success) {
      // Interval correction must be present and surfaced (spec B3).
      expect(res.data.durations[0].correctionApplied).toBe(true);
      expect(res.data.durations[0].correctionFactor).toBeCloseTo(1.13);
    }
  });

  it("qc-infill fixture validates", () => {
    const f = fixture("qc-infill.json");
    expect(InfillRequest.safeParse(f.request).success).toBe(true);
    const res = InfillResponse.safeParse(f.response);
    expect(res.success).toBe(true);
    if (res.success) expect(res.data.filledPoints.length).toBeGreaterThan(0);
  });
});
