"""Golden-value tests for trend/homogeneity (spec §6 M2 acceptance).

Reference values generated by scripts/generate_goldens.py on 2026-07-04 using:
- pymannkendall 1.4.3  (original_test, sens_slope conventions)
- pyhomogeneity 1.1    (pettitt_test, snht_test, sim=20000)

Deterministic statistics (S, var_S, Z, tau, slope, intercept, K, T0, change
point) are asserted tightly. Reference Monte-Carlo p-values are unseeded, so
those get wide tolerances; our own MC (SNHT) is seeded and deterministic.

Convention note: pyhomogeneity reports the change point as the 1-based count
of values in the first segment; ours is the 0-based index of the last point
before the shift → ref_cp == ours.change_point_index + 1.
"""

import numpy as np
import pytest

from core_engine.qc.trend import mann_kendall, pettitt, snht
from canonical import CANONICAL_PRECIP, CANONICAL_STABLE


class TestMannKendallGolden:
    def test_precip_matches_pymannkendall(self):
        r = mann_kendall(CANONICAL_PRECIP)
        assert r.trend == "increasing"
        assert r.significant is True
        assert r.s == pytest.approx(723.0)
        assert r.var_s == pytest.approx(14289.666666666666)
        assert r.z == pytest.approx(6.039849936783064, abs=1e-12)
        assert r.p_value == pytest.approx(1.5425762889265116e-09, rel=1e-9)
        assert r.tau == pytest.approx(0.590204081632653, abs=1e-12)
        assert r.sen_slope == pytest.approx(5.063333333333333, abs=1e-12)
        assert r.sen_intercept == pytest.approx(421.8983333333334, abs=1e-9)

    def test_stable_matches_pymannkendall(self):
        r = mann_kendall(CANONICAL_STABLE)
        assert r.trend == "no_trend"
        assert r.significant is False
        assert r.s == pytest.approx(-8.0)
        assert r.var_s == pytest.approx(950.0)
        assert r.z == pytest.approx(-0.22710998958306755, abs=1e-12)
        assert r.p_value == pytest.approx(0.8203382164336168, abs=1e-12)
        assert r.sen_slope == pytest.approx(-0.10119047619047483, abs=1e-12)

    def test_s_statistic_brute_force(self):
        """Independent check: S recomputed pair-by-pair."""
        x = np.asarray(CANONICAL_PRECIP)
        s = sum(
            np.sign(x[j] - x[i]) for i in range(len(x) - 1) for j in range(i + 1, len(x))
        )
        assert mann_kendall(CANONICAL_PRECIP).s == pytest.approx(float(s))


class TestPettittGolden:
    def test_precip_matches_pyhomogeneity(self):
        r = pettitt(CANONICAL_PRECIP)
        assert r.k == pytest.approx(606.0)
        # ref cp=24 (1-based count) → 0-based last-index 23
        assert r.change_point_index == 23
        assert r.mean_before == pytest.approx(488.4583333333333, abs=1e-9)
        assert r.mean_after == pytest.approx(640.3307692307693, abs=1e-9)
        # ref MC p = 0.0; our closed-form approximation ≈ 6e-8
        assert r.p_value < 1e-4
        assert r.homogeneous is False

    def test_stable_matches_pyhomogeneity(self):
        r = pettitt(CANONICAL_STABLE)
        assert r.k == pytest.approx(15.0)
        assert r.change_point_index == 8  # ref cp=9
        assert r.mean_before == pytest.approx(501.27777777777777, abs=1e-9)
        assert r.mean_after == pytest.approx(499.35454545454553, abs=1e-9)
        # ref MC p = 0.99935; our approximation caps at 1.0
        assert r.p_value > 0.95
        assert r.homogeneous is True


class TestSnhtGolden:
    def test_precip_matches_pyhomogeneity(self):
        r = snht(CANONICAL_PRECIP, mc_samples=5000, seed=42)
        assert r.t0 == pytest.approx(30.22470320470419, abs=1e-9)
        # ref cp=25 (count) → 0-based last-index 24
        assert r.change_point_index == 24
        assert r.mean_before == pytest.approx(490.81199999999995, abs=1e-9)
        assert r.mean_after == pytest.approx(644.052, abs=1e-9)
        assert r.p_value < 0.01  # ref MC p = 0.0
        assert r.homogeneous is False

    def test_stable_matches_pyhomogeneity(self):
        r = snht(CANONICAL_STABLE, mc_samples=5000, seed=42)
        assert r.t0 == pytest.approx(1.034843138015298, abs=1e-9)
        assert r.p_value == pytest.approx(0.9787, abs=0.03)  # ref MC, unseeded
        assert r.homogeneous is True

    def test_seeded_mc_is_reproducible(self):
        a = snht(CANONICAL_PRECIP, mc_samples=2000, seed=7)
        b = snht(CANONICAL_PRECIP, mc_samples=2000, seed=7)
        assert a.p_value == b.p_value
